#!/bin/bash

curr_dir="$(cd "$(dirname "$0")" && pwd)"
cd "$curr_dir" || exit
cd ..
date > /tmp/last_update.log
git pull origin macless >> /tmp/last_update.log
git merge origin/macless >> /tmp/last_update.log