name: macless_haystack
description: Macless Haystack

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_colorpicker: ^1.1.0
#  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^4.0.0

  # Networking
  http: ^1.3.0
  universal_html: ^2.2.4

  # Cryptography
  # latest version of pointy castle for crypto functions
  pointycastle: ^3.9.1

  # State Management
  provider: ^6.1.2

  # Location
  universal_io: ^2.2.2
  flutter_map: ^8.0.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  location: ^8.0.0
  geocoding: ^3.0.0
  visibility_detector: ^0.4.0+2

  # Storage
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  file_picker: ^8.3.7

  # Sharing
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  maps_launcher: ^3.0.0+1


  flutter_settings_screens: ^0.3.4
  latlong2: ^0.9.1
  intl: ^0.20.2
  logger: ^2.5.0


dev_dependencies:

  dependency_validator: ^5.0.2
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  test: ^1.25.15
  mockito: ^5.4.5

# Configuration for flutter_launcher_icons
flutter_icons:
  android: true
  ios: false
  image_path: "assets/OpenHaystackIcon.png"
  web:
    generate: true
    image_path: "assets/OpenHaystackIcon.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
